language: android
jdk: openjdk7
sudo: false

android:
    components:
        - platform-tools
        - tools
        - build-tools
        - android-16
        - extra-android-m2repository

env:
    global:
        - ANDROID_TARGET_SDK=16

script:
    - for i in /usr/local/android-sdk-*/; do export SDK_PATH="$i"; done
    - for i in "$SDK_PATH"/build-tools/*.*.*/; do export SDK_BUILD_TOOLS="$i"; done
    - for i in "$SDK_PATH"/extras/android/m2repository/com/android/support/support-v4/*.*.*/support-v4-*.*.*.aar; do export SUPPORT_AAR="$i"; done
    - for i in "$SDK_PATH"/extras/android/m2repository/com/android/support/recyclerview-v7/*.*.*/recyclerview-v7-*.*.*.aar; do export RECYCLERVIEW_AAR="$i"; done
    - export LIB_AARS="$SUPPORT_AAR $RECYCLERVIEW_AAR"
    - make
